services:
  gnucash-web:
    image: ghcr.io/williamjacksn/gnucash-web
    init: true
    ports:
      - 8080:8080

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/gnucash-web
    init: true
    volumes:
      - ./:/home/python/docker-gnucash-web
    working_dir: /home/python/docker-gnucash-web
