name: Generate requirements.txt with pip-compile

on:
  push:
    branches:
      - main
    paths:
      - requirements.in
  workflow_dispatch:

jobs:
  pip-compile:
    name: Generate requirements.txt with pip-compile
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: pip
          python-version: '3.11'

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Run pip-compile
        run: pip-compile

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          body: Generate requirements.txt with `pip-compile`
          branch: pip-compile
          commit-message: Generate requirements.txt with `pip-compile`
          delete-branch: true
          title: Generate requirements.txt with `pip-compile`
          token: ${{ secrets.personal_token }}
